# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 00:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0001_squashed_0004_auto_20170529_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='province',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
