# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0002_auto_20170529_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_line',
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
