# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0003_auto_20170602_0107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='Location',
        ),
    ]
