# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0003_auto_20170407_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([('last_name', 'first_name', 'middle_name')]),
        ),
    ]
