# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0003_auto_20170529_0145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(default='', max_length=100),
        ),
    ]
