# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 01:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0004_auto_20170602_0126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
    ]
