# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0005_auto_20170602_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_kind', models.SmallIntegerField(choices=[(1, 'Home Address'), (2, 'Work Address'), (3, 'Other Address')], default=1, verbose_name='Type')),
                ('address_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='receivables.Location')),
                ('address_of', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='receivables.Person')),
            ],
        ),
    ]
