# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0006_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_detail',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_kind',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_of',
        ),
        migrations.AddField(
            model_name='address',
            name='barangay',
            field=models.CharField(default='', max_length=100, verbose_name='Barangay / District'),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='City / Municipality'),
        ),
        migrations.AddField(
            model_name='address',
            name='kind',
            field=models.SmallIntegerField(default=1, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.CharField(default='', max_length=100, verbose_name='Province / Region'),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(default='', max_length=100, verbose_name='Street Address'),
        ),
        migrations.AddField(
            model_name='address',
            name='zipcode',
            field=models.CharField(default='', max_length=20, verbose_name='ZIP Code'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
