# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0007_auto_20170602_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='kind',
            field=models.SmallIntegerField(choices=[(1, 'Home Address'), (2, 'Work Address'), (3, 'Other Address')], default=1, verbose_name='Type'),
        ),
    ]
