# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0008_auto_20170602_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='person',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='receivables.Person'),
            preserve_default=False,
        ),
    ]
