# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 02:55
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receivables', '0009_address_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receivables.Account')),
                ('created_by', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='receivables_transaction_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='receivables_transaction_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
