# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0011_auto_20170605_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=12),
        ),
    ]
