# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asimplemenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='link',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
