# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asimplemenu', '0003_menuitem_seqence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['sequence']},
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='seqence',
            new_name='sequence',
        ),
    ]
