# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asimplemenu', '0004_auto_20170227_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
                ('description', models.CharField(default='', max_length=80)),
            ],
        ),
        migrations.RenameModel(
            old_name='MenuItem',
            new_name='Item',
        ),
    ]
