# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asimplemenu', '0005_auto_20170320_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='groups',
            field=models.ManyToManyField(related_name='group', to='asimplemenu.Group'),
        ),
    ]
