# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asimplemenu', '0006_item_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='load',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asimplemenu.Group'),
            preserve_default=False,
        ),
    ]
