# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asimplemenu', '0007_item_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asimplemenu.Group'),
        ),
    ]
