# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asimplemenu', '0008_auto_20170321_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='groups',
            field=models.ManyToManyField(related_name='items', to='asimplemenu.Group'),
        ),
    ]
