# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asimplemenu', '0010_auto_20170406_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asimplemenu.Group'),
        ),
    ]
